name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: Config Git
      run: |
        git config --global user.email "${{github.actor}}@users.noreply.github.com"
        git config --global user.name "${{github.actor}}"
        git remote set-url origin "https://${{github.actor}}:${{github.token}}@github.com/${{github.repository_owner}}/${{github.repository}}.git/"
    
    - name: Install
      run: npm install
    
    - name: Build
      run: npm run build
      
    - name: Deploy
      
