name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: |
        git config --local user.email "${{github.actor}}@users.noreply.github.com"
        git config --local user.name "${{github.actor}}"
    - run: npm run deploy
